### ISSUE TITLE
Latitude does not support Southern Hemisphere 

### ISSUE THREAD

**Issue by carlsteyn73** [kortel-systems/hyteratak#1]
Coordinates which are in the Southern Hemisphere are pushed to TAK as Northern Hemisphere coordinates

**Comment by tomek-sienicki** [comment]
Hi @carlsteyn73,
we have fixed it in the newest version v1.1.1, just upgrade the module and you are all set 🐘

**Comment by carlsteyn73** [comment]
Hey @tomek-sienicki !

Thank you very much! Appreciated
